# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 이희성
title: Junior DevOps Engineer
phone: +821089259242
email: lscc1504@g.kmou.ac.kr
website: https://thereisnotherway.tistory.com/
website_title: Blog

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: mason0920
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: mason0920
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: fab fa-twitter
#   url: https://google.com

# Google Analytics and Tag Manager
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_profile_image: images/profile.jpg
about_content: |
  ## **Introduction**

  "한번 떨어진 신뢰는 회복하기 힘들다"라는 신념 아래, 반복 검증과 교차 검증을 통해 실수를 최소화하며 장애 없는 인프라 운영을 추구해왔습니다.  
  코딩을 통해 문제 해결과 업무 자동화를 실현하며, 항상 최적의 성능과 안정성을 우선으로 생각합니다.  
  대학교에서 AI 빅데이터 연계전공을 수강하며 컴퓨터 공학 기초를 다졌고, 코드스테이츠 DevOps 부트캠프를 통해 실무 역량을 강화하였습니다.

  ---

  ## **How I Learn**

  - [<u>문제 발생 시 분석 및 해결</u>](https://thereisnotherway.tistory.com/51): 에러 상황을 철저히 분석하고 해결책을 도출합니다.
  - [<u>자체 학습 및 정리</u>](https://www.notion.so/TIL-Today-I-Learned-877df2c605464a6ca94746b798559966): 새로운 개념에 대해 스스로 묻고 답하며 정리합니다.
  - [<u>칸반 보드를 활용한 협업</u>](https://gigantic-thistle-8c2.notion.site/5a8764775a1e42f59838e070e73f4ce0): 체계적인 협업을 통해 프로젝트를 진행합니다.

  ---

  ## **My Goal**

  - 100만 MAU 이상의 서비스를 안정적으로 운영하는 인프라 구축
  - 클라우드 비용 최적화를 위해 서버리스와 자동화 기술 적극 활용
  - 지속적인 테스트 코드 작성 및 CI/CD 개선을 통한 빠른 배포와 안정성 확보
  - 경험과 성과를 공유하며 성장하는 DevOps 전문가로 거듭나기

content:
  - title: Skills
    layout: list
    content:
      - layout: top-middle
        title: DevOps & Automation
        description: |
          - Docker, Kubernetes, Karpenter, GitOps (ArgoCD, Helm)
          - Git, Shell Scripting, Jenkins, GitHub Actions
          - Terraform, Prometheus, Grafana, k6
      - layout: top-middle
        title: Cloud Platforms
        description: |
          - AWS (EC2, Lambda@Edge, ECS, ECR, S3, CloudFront, CloudWatch, VPC, API Gateway, Route53, SQS, SNS)
          - GCP
      - layout: top-middle
        title: Backend & Programming
        description: |
          - Node.js, Go, Java
          - Express.js, Fastify
          - MySQL, MongoDB, Redis, ElasticSearch
      - layout: top-middle
        title: Others
        description: |
          - Linux (Ubuntu)
          - Git, Shell Script

  - title: Experience
    layout: list
    content:
      - layout: left
        title: 주식회사 마켓보로
        sub_title: Kube Native App 개발 및 클라우드 인프라 운영
        caption: 2023.08 - 현재
        description: |
          **신뢰 기반 인프라 운영**
          - **Scheduler 개발 (Golang):**  
            사내 테스트 자동화 프로그램에서 브라우저 테스트를 무한 확장 가능하도록 Pod를 띄우고, 실행 결과와 로그를 실시간으로 확인할 수 있는 Scheduler 개발.
          - **CronJob Manager 개발 (Golang):**  
            CronJob 실행 및 관리 체계 구축을 통한 업무 자동화 향상.
          - **페이지 속도 개선 (2025.01 - 2025.03):**  
            CDN + Lambda@Edge를 활용하여 이미지 확장자 변환 및 크기 조절 함수 개발, 이미지 다수 페이지의 로딩 속도를 33% 개선.
          - **오픈소스 활용 (2024.07 - 2024.09):**  
            ElasticSearch, Redis Cluster, Airflow, Redash, Growthbook, Prometheus, Grafana, Loki, Kubecost 등 다양한 오픈소스 솔루션을 Kubernetes에서 호스팅 및 운영.
          - **Kubernetes 도입 (2024.04 - 2024.12):**  
            ArgoCD를 통한 GitOps 구현, Helm Chart 구성 및 Karpenter + Spot Instance를 활용한 인프라 비용 최적화.
          - **모니터링 시스템 도입 (2024.01 - 2024.12):**  
            Prometheus + Grafana를 사용해 인프라 메트릭 중앙화, Prometheus Alert + Slack 연동 및 Loki + S3를 통한 로그 관리로 안정적 운영 기여.

      - layout: left
        title: 주식회사 와탭랩스
        sub_title: 테스트 자동화 및 SaaS 운영
        caption: 2023.04 - 2024.06
        description: |
          - **테스트 자동화:**  
            EKS에 Selenium Grid 구성, Selenium UI 테스트 스크립트 작성, 배포 시 테스트 실행 및 Prometheus와 Slack 연동을 통한 결과 가시화.
          - **SaaS 운영:**  
            Java 애플리케이션 장애 상황 대응 및 분석, Disk full 및 OOM 상황 분석을 통한 병목 인지 및 대응, 관련 보고서 작성.

      - layout: left
        title: 코드스테이츠 DevOps 부트캠프
        sub_title: 실무 역량 강화 교육
        caption: 2022.02 - 2022.06
        description: |
          - Docker, Kubernetes, Git, Shell Scripting 등 DevOps 핵심 기술 습득.
          - GitHub Actions, Terraform, Prometheus, Grafana 등을 활용한 배포 자동화 및 모니터링 시스템 구축 경험.

  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: 한국해양대학교
        caption: 2016 - 2022
        sub_title: 국제무역경제학사, AI 빅데이터 연계전공

  - title: A Little More About Me
    layout: text
    content: |
      개발 외에도 스트레스 관리를 위해 건강한 취미 생활을 즐깁니다!
      - [<u>낚시</u>](https://blog.naver.com/lscc1503)
      - [<u>독서 모임</u>](./images/reading.jpeg)
      - [<u>러닝</u>](./images/running.jpeg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
